# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180607_1825'),
        ('checker', '0009_isabelle_checker_trusted_to_additional_theories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTF8Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(help_text='Determines the order in wich the checker will start. Not necessary continuously!')),
                ('public', models.BooleanField(default=True, help_text='Test results are displayed to the submitter.')),
                ('required', models.BooleanField(default=False, help_text='The test must be passed to submit the solution.')),
                ('always', models.BooleanField(default=True, help_text='The test will run on submission time.')),
                ('critical', models.BooleanField(default=False, help_text='If this test fails, do not display further test results.')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fortranbuilder',
            name='task',
        ),
        migrations.RemoveField(
            model_name='haskellbuilder',
            name='task',
        ),
        migrations.RemoveField(
            model_name='haskelltestframeworkchecker',
            name='task',
        ),
        migrations.RemoveField(
            model_name='ignoringhaskellbuilder',
            name='haskellbuilder_ptr',
        ),
        migrations.RemoveField(
            model_name='isabellechecker',
            name='task',
        ),
        migrations.RemoveField(
            model_name='rchecker',
            name='task',
        ),
        migrations.RemoveField(
            model_name='scalabuilder',
            name='task',
        ),
        migrations.RemoveField(
            model_name='testonlybuildingbuilder',
            name='haskellbuilder_ptr',
        ),
        migrations.AlterField(
            model_name='junitchecker',
            name='ignore',
            field=models.CharField(blank=True, default=b'', help_text='space-seperated list of files to be ignored during compilation, i.e.: these files will not be compiled.', max_length=4096),
        ),
        migrations.DeleteModel(
            name='FortranBuilder',
        ),
        migrations.DeleteModel(
            name='HaskellBuilder',
        ),
        migrations.DeleteModel(
            name='HaskellTestFrameWorkChecker',
        ),
        migrations.DeleteModel(
            name='IgnoringHaskellBuilder',
        ),
        migrations.DeleteModel(
            name='IsabelleChecker',
        ),
        migrations.DeleteModel(
            name='RChecker',
        ),
        migrations.DeleteModel(
            name='ScalaBuilder',
        ),
        migrations.DeleteModel(
            name='TestOnlyBuildingBuilder',
        ),
    ]
